Add MySQL database support
cen4010/geek-text-webapp pull request #46
Opened 2018-04-06 06:20 UTC by ogonz110

This PR allows the use of a remotely-hosted MySQL (or MariaDB) database, configured through these environment variables:

```
export DB_BACKEND=mysql
export DB_NAME=[database name]
export DB_USER=[username]
export DB_PASSWORD=[password]
export DB_HOST=[hostname (localhost if hosted on the same machine)]
export DB_PORT=[port (3306 is the default for MySQL)]
```

2018-04-06 12:47 UTC, fhern077 approved these changes
Seems good . Any  suggestions for setting the environment vars python-dotenv in virtual env, setting through command line, having .env file or setting up some sort of settings module??

2018-04-07 01:10 UTC, loksonarius approved these changes
Looks great 👌 works for what we need

2018-04-07 01:13 UTC, loksonarius requested changes
Please add documentation on these variables to the dev directory

2018-04-07 04:22 UTC, loksonarius approved these changes

2018-04-07 04:30 UTC, merged